#!/bin/bash
# Let Omarchy run its screensaver in WezTerm.
#
# Omarchy's "screensaver" is a fullscreen terminal running omarchy-screensaver,
# which animates Omarchy's branding with ttfx. omarchy-launch-screensaver
# hardcodes an allow-list of host terminals and otherwise refuses, so WezTerm has
# to be added to it. That script lives under /usr/share/omarchy/bin, which comes
# before ~/.local/bin on PATH, so there is no user-level override: this target
# needs root and has no --local counterpart.
#
# usage: install-screensaver.sh --global

set -euo pipefail
# shellcheck source=common.sh
source "$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)/common.sh"

parse_scope_args "$@"

if [[ $SCOPE != global ]]; then
  # Explicitly, rather than silently doing nothing: this is the one feature that
  # genuinely cannot be installed per-user.
  die "the screensaver host list lives in $PREFIX/bin, which a user cannot override.
    Use --global (with root) for this feature; every other target works --local."
fi

launcher="$PREFIX/bin/omarchy-launch-screensaver"
ss_lua_dst="$PREFIX/default/wezterm/screensaver.lua"

[[ -f $launcher ]] || die "not found: $launcher (is Omarchy installed?)"

if grep -qF '*wezterm*' "$launcher"; then
  say "WezTerm is already an accepted screensaver host"
  install_file "$FILES/screensaver.lua" "$ss_lua_dst"
  exit 0
fi

say "adding WezTerm to the screensaver host list"

tmp_dir="$(mktemp -d)"
tmp="$tmp_dir/launcher"

# Three edits, all idempotent by virtue of the early exit above:
#   1. accept WezTerm in the allow-list case, so it stops refusing
#   2. add a *wezterm*) branch mirroring the Alacritty one
#   3. mention WezTerm in the "only runs in ..." notification
#
# On the gist's --always-new-process and --class: both are required, not
# cosmetic. Without --always-new-process a running WezTerm GUI hosts the window
# and silently ignores --config-file, so the screensaver config would not apply;
# and --class org.omarchy.screensaver is what omarchy-launch-screensaver's
# wait_for_screensaver_window and omarchy-screensaver's focus check match on.
#
# The gist also patched GRACE_SECONDS into omarchy-screensaver to survive a
# multi-monitor focus race. That is deliberately not done here: this Omarchy
# version already fixes it in wait_for_screensaver_window, which blocks until
# each monitor's window has mapped before moving focus on. See
# install-screensaver-grace.sh if you still hit the race.
awk '
  /^[[:space:]]*\*Alacritty\* \| \*ghostty\* \| \*foot\* \| \*kitty\*\)[[:space:]]*;;[[:space:]]*$/ {
    print "*Alacritty* | *ghostty* | *foot* | *kitty* | *wezterm*) ;;"
    allow = 1
    next
  }
  /Screensaver only runs in Alacritty, Foot, Ghostty, or Kitty/ {
    sub(/Screensaver only runs in Alacritty, Foot, Ghostty, or Kitty/,
        "Screensaver only runs in Alacritty, Foot, Ghostty, Kitty, or WezTerm")
    print
    notify = 1
    next
  }
  /^[[:space:]]*\*kitty\*\)[[:space:]]*$/ { print; after_kitty = 1; next }
  after_kitty && /^[[:space:]]*;;[[:space:]]*$/ {
    print
    print "  *wezterm*)"
    print "    hypr_exec wezterm-gui --config-file \"$OMARCHY_PATH/default/wezterm/screensaver.lua\" start --always-new-process --class org.omarchy.screensaver -- omarchy-screensaver"
    print "    ;;"
    after_kitty = 0
    branch = 1
    next
  }
  { print }
  END {
    if (!allow) print "WEZTERM_OMARCHY_WARN=allow" > "/dev/stderr"
    if (!branch) print "WEZTERM_OMARCHY_WARN=branch" > "/dev/stderr"
    if (!notify) print "WEZTERM_OMARCHY_WARN=notify" > "/dev/stderr"
  }
' "$launcher" >"$tmp" 2>"$tmp_dir/warnings"

# The script is generated by Omarchy and may be reshaped by an update, so verify
# every edit actually landed instead of installing a half-patched file.
missing=""
grep -qF '| *wezterm*) ;;' "$tmp" || missing="$missing allow-list"
grep -qF '*wezterm*)' "$tmp" || missing="$missing branch"
grep -qF 'Kitty, or WezTerm' "$tmp" || missing="$missing notification"

if [[ -n $missing ]]; then
  rm -rf -- "$tmp_dir"
  die "could not patch $launcher (failed:$missing).
    Its shape has probably changed since this script was written.
    Compare it with the 'case $terminal in' blocks and update
    scripts/install-screensaver.sh accordingly."
fi

save_original "$launcher"
install_file "$FILES/screensaver.lua" "$ss_lua_dst"
install_patched_script "$tmp" "$launcher"
rm -rf -- "$tmp_dir"

warn "$launcher is owned by the Omarchy package; an update may revert this patch."
warn "Re-run 'make install-screensaver-global' if it does."
